
pipeline {
		def functions = load("cicd/functions.groovy")
		agent any
		stages {
				stage('Env Variables') {
						steps {
								sh 'printenv'
						}
				}
				stage('Build') {
						steps {
								echo 'Building...'
						}
				}
				stage('Tagging') {
            steps {
							script {
                functions.tagBuild()
							}
            }
        }
				stage('Test') {
						steps {
								echo 'Testing...'
						}
				}
				stage('Deploy') {
						steps {
								echo 'Deploying....'
						}
				}
		}
}