pipeline {
    agent any
    stages {
        stage('Services') {
            parallel {
                stage('Server') {
										when { expression { load("cicd/hasChanges.groovy").checkChanges('services/server') } }
                    stages {
                        stage('Pre Build') { steps { sh 'services/server/scripts/pre-build.sh' } }
												stage('Build') { steps { sh 'services/server/scripts/build.sh' } }
                    }
                }
                stage('Client') {
										when { expression { load("cicd/hasChanges.groovy").checkChanges('services/client') } }
                    stages {
                        stage('Pre Build') { steps { sh 'services/client/scripts/pre-build.sh' } }
												stage('Build') { steps { sh 'services/client/scripts/build.sh' } }
                    }
                }
								stage('Hasura') {
										when { expression { load("cicd/hasChanges.groovy").checkChanges('services/hasura') } }
                    stages {
                        stage('Pre Build') { steps { sh 'services/hasura/scripts/pre-build.sh' } }
												stage('Build') { steps { sh 'services/hasura/scripts/build.sh' } }
                    }
                }
								stage('DB') {
										when { expression { load("cicd/hasChanges.groovy").checkChanges('services/db') } }
                    stages {
                        stage('Pre Build') { steps { sh 'services/db/scripts/pre-build.sh' } }
												stage('Build') { steps { sh 'services/db/scripts/build.sh' } }
                    }
                }
            }
        }
				stage('Deploy Environment') {
					steps {
						echo 'Deploying to production environment...'
					}
				}
				stage('E2E Tests') {
					steps {
						echo 'Running e2e tests...'
					}
				}
    }
}
