apiVersion: v1
kind: ConfigMap
metadata:
  name: ${NAMESPACE}-config
  namespace: ${NAMESPACE}
data:
  # SERVER
  VITE_SERVER_ENDPOINT: ${VITE_SERVER_ENDPOINT}
  SERVER_PORT: ${SERVER_PORT}
  # HASURA
  VITE_HASURA_GQL_ENDPOINT: ${VITE_HASURA_GQL_ENDPOINT}
  HASURA_ENDPOINT: ${HASURA_ENDPOINT}
  HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
  HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: ${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}
  HASURA_METADATA_DATABASE_URL: ${HASURA_METADATA_DATABASE_URL}
  HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
  HASURA_GRAPHQL_ENABLE_CONSOLE: ${HASURA_GRAPHQL_ENABLE_CONSOLE}
  HASURA_GRAPHQL_DEV_MODE: ${HASURA_GRAPHQL_DEV_MODE}
  # POSTGRES
  PG_URL: ${PG_URL}
  PG_HOST: ${PG_HOST}
  PG_USERNAME: ${PG_USERNAME}
  PG_PASSWORD: ${PG_PASSWORD}
  PG_PORT: ${PG_PORT}
  PG_DATABASE: ${PG_DATABASE}
  PG_SSL: ${PG_SSL}
  # FIREBASE
  VITE_FB_API_KEY: ${VITE_FB_API_KEY}
  VITE_FB_AUTH_DOMAIN: ${VITE_FB_AUTH_DOMAIN}
  VITE_FB_PROJECT_ID: ${VITE_FB_PROJECT_ID}
  VITE_FB_STORAGE_BUCKET: ${VITE_FB_STORAGE_BUCKET}
  VITE_FB_MESSAGING_SENDER_ID: ${VITE_FB_MESSAGING_SENDER_ID}
  VITE_FB_APP_ID: ${VITE_FB_APP_ID}
  FIREBASE_PROJECT_ID_DEV: ${FIREBASE_PROJECT_ID_DEV}
  FIREBASE_SERVICE_ACCOUNT_JSON_DEV: ${FIREBASE_SERVICE_ACCOUNT_JSON_DEV}
  # KUBERNETES (Consider storing large config like KUBE_CONFIG in a secret rather than a ConfigMap)
  KUBE_CONFIG: ${KUBE_CONFIG}
